Update upload_forecasts.yml

diff --git a/.github/workflows/upload_forecasts.yml b/.github/workflows/upload_forecasts.yml
--- a/.github/workflows/upload_forecasts.yml
+++ b/.github/workflows/upload_forecasts.yml
@@ -92,11 +92,14 @@ jobs:
           python ./tools/code/clear_data_storage.py --storage_type "model-output" 
 
       # ERROR RUN
+      # exit with error to prevent from running the rest of the workflow chain
+      # this will skip also the final commit step
       # --------------------------------------------
       - name: Error
         if: ${{ steps.invoke_webhook.outputs.run_results.status == 'error'}}
         run: |
-          echo "UPLOAD FAILED -  ignore djson db cleaning"
+          echo "UPLOAD FAILED -  ignore djson db cleaning"          
+          exit 1
 
       # Final commit
       # --------------------------------------------
